name: Build & Sign TV Bro (genericRelease)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      # 1) Generar keystore efímero para la firma de "release"
      - name: Generate release keystore
        run: |
          keytool -genkeypair -v \
            -keystore release.jks \
            -storepass 123456 \
            -keypass 123456 \
            -alias release \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=TVBro, OU=PRL, O=PRL, L=Arequipa, ST=Arequipa, C=PE"

      # 2) Definir propiedades de firma + memoria para Gradle (leídas por app/build.gradle)
      - name: Write gradle.properties (signing + memory)
        run: |
          cat > gradle.properties << 'EOF'
          # Firma de release (usada por signingConfigs.release en app/build.gradle)
          RELEASE_STORE_FILE=release.jks
          RELEASE_STORE_PASSWORD=123456
          RELEASE_KEY_ALIAS=release
          RELEASE_KEY_PASSWORD=123456

          # Memoria extra para Gradle/Kotlin/Lint
          org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
          kotlin.daemon.jvmargs=-Xmx2g
          org.gradle.daemon=true
          org.gradle.parallel=true
          org.gradle.configureondemand=true
          EOF

      # 3) Compilar SOLO genericRelease para evitar el flavor fossRelease que fallaba
      - name: Build genericRelease
        run: ./gradlew :app:assembleGenericRelease --no-daemon

      # 4) Listar APKs generados para verificar rutas
      - name: List generated APKs
        run: |
          echo "===== APKs ====="
          find app/build/outputs/apk -type f -name "*generic*release*.apk" -printf "%p\n" | sort -V || true

      # 5) Subir el/los APK firmados por Gradle (ya quedan firmados con el keystore efímero)
      - name: Upload signed APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: tvbro-generic-release-signed
          path: |
            app/build/outputs/apk/generic/release/*.apk
